### ISSUE TITLE
"Error: Assertion Failed: Could not find adapter LocalError" when I run unit test

### ISSUE THREAD

**Issue by dennis-jiang** [tomasbasham/ember-cli-persistence#1]
Here is my codes:

```
...
  persistence: inject.service(),

  init(...args) {
    this._super(...args);

    const persistence = get(this, 'persistence');
    persistence.getItem('Local', { key: get(this, 'searchValueKey') })
    .then(value => value);
  }
...
```

And my test codes:
```
...
needs: [
      'service:persistence'
    ]
...

it('should run well', function () {
    const controller = this.subject();
    expect(controller).to.be.ok;
  });
...
```

It is very simple, but I got this error:  
```
Error: Assertion Failed: Could not find adapter LocalError
    at assert (http://localhost:7357/assets/vendor.js:25469:13)
    at assert (http://localhost:7357/assets/vendor.js:37220:34)
    at Class.activateAdapter (http://localhost:7357/assets/vendor.js:154725:7)
    at http://localhost:7357/assets/vendor.js:154698:75
    at Array.forEach (<anonymous>)
    at Class.activateAdapters (http://localhost:7357/assets/vendor.js:154695:22)
    at Class.createAdapters (http://localhost:7357/assets/vendor.js:161697:12)
    at Object.sendEvent (http://localhost:7357/assets/vendor.js:37748:25)
    at new Class (http://localhost:7357/assets/vendor.js:56076:21)
    at Function._ClassMixinProps.create (http://localhost:7357/assets/vendor.js:56262:12)
```

Could you help me?

Thanks!

**Comment by tomasbasham** [comment]
May I assume you have included the necessary [configuration](https://github.com/tomasbasham/ember-cli-persistence#example)

**Comment by tomasbasham** [comment]
You may also want to include `ember-cli-persistence@container:local` within the `needs` array on your tests. This will pull in the specific container you are trying to use
